Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,5 @@
 version: 2.1
-  
+
 commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
@@ -79,7 +79,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-      - checkout    
+      - checkout
       - restore_cache:
           keys:
             - "frontend-build"
@@ -88,11 +88,7 @@ jobs:
           command: |
             cd frontend
             npm i
-            npm run test 
-        
-        
-        
-               
+            npm run test
 
   test-backend:
     docker:
@@ -102,7 +98,7 @@ jobs:
       # Checkout code from git
       # Restore from cache
       # Your job code here
-    
+
       - checkout
       - restore_cache:
           keys:
@@ -112,8 +108,8 @@ jobs:
           command: |
             cd backend
             npm i
-            npm run test 
-      
+            npm run test
+
   scan-frontend:
     docker:
       # Docker image here
@@ -125,11 +121,11 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - "frontend-build" 
-      - run: 
-              command: |
-                  cd frontend
-                  npm audit --audit-level=critical
+            - "frontend-build"
+      - run:
+          command: |
+            cd frontend
+            npm audit --audit-level=critical
 
   scan-backend:
     docker:
@@ -142,12 +138,12 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - "backend-build" 
-      - run: 
-              command: |
-                  cd backend
-                  npm audit fix --audit-level=critical --force
-      
+            - "backend-build"
+      - run:
+          command: |
+            cd backend
+            npm audit fix --audit-level=critical --force
+
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
@@ -158,20 +154,18 @@ jobs:
       - run:
           name: Ensure back-end infrastructure exists
           command: |
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              # exit 1
-              # aws cloudformation deploy \
-              #  --template-file .circleci/files/estcfn.yml \
-              #  --stack-name my-stack-circleci
-              aws cloudformation deploy \
-                --template-file .circleci/files/backend.yml \
-                --stack-name backend-stack-$CIRCLE_WORKFLOW_ID \
-                --parameter-overrides ID=$CIRCLE_WORKFLOW_ID
-                           
-                           
-              
+            #--tags project=your-tag \
+            # --stack-name "your back-end stack name with workflow id" \
+            # --parameter-overrides ID="your workflow id"  
+            # exit 1
+            # aws cloudformation deploy \
+            #  --template-file .circleci/files/estcfn.yml \
+            #  --stack-name my-stack-circleci
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --stack-name backend-stack-$CIRCLE_WORKFLOW_ID \
+              --parameter-overrides ID=$CIRCLE_WORKFLOW_ID
+
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -184,12 +178,12 @@ jobs:
               aws cloudformation deploy \
                 --template-file .circleci/files/frontend.yml \
                 --stack-name frontend-stack-$CIRCLE_WORKFLOW_ID \
-                --parameter-overrides ID=$CIRCLE_WORKFLOW_ID 
-                
+                --parameter-overrides ID=$CIRCLE_WORKFLOW_ID
+
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-          
+
             echo "[web]" > inventory
             aws cloudformation describe-stacks \
             --stack-name "backend-stack-${CIRCLE_WORKFLOW_ID}" \
@@ -198,7 +192,7 @@ jobs:
             # Your code here
             # exit 1
       - run: yum install -y tar gzip
-      
+
       - persist_to_workspace:
           root: ~/
           paths:
@@ -214,61 +208,55 @@ jobs:
       # Add ssh keys with fingerprint
       # attach workspace
       steps:
-      - add_ssh_keys:
-          fingerprints: [77:50:06:fa:0d:9f:b2:0e:66:6a:46:6a:5d:68:36:b1]
-      - checkout
-      - restore_cache:
-          keys: 
-            - back-end-{{ checksum "backend/package.json" }}
+        - add_ssh_keys:
+            fingerprints: [77:50:06:fa:0d:9f:b2:0e:66:6a:46:6a:5d:68:36:b1]
+        - checkout
+        - restore_cache:
+            keys:
+              - back-end-{{ checksum "backend/package.json" }}
 
-      - run: apk add tar gzip
-      - attach_workspace:
-          at: ./
-      - run: mkdir -p  .circleci/ansible/roles/configure-server/files/backend
-      - run:
-          name: Make .env file
-          command: |
-            cd backend
-            echo "ENVIRONMENT=production" > env
-            echo "NODE_ENV=production" >> env
-            echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> env
-            echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> env
-            echo "TYPEORM_HOST=$TYPEORM_HOST" >> env
-            echo "TYPEORM_PORT=$TYPEORM_PORT" >> env
-            echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> env
-            echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> env
-            echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> env
-      
-      
-      
-      - run:
-          name: Install dependencies
-          command: |
+        - run: apk add tar gzip
+        - attach_workspace:
+            at: ./
+        - run: mkdir -p  .circleci/ansible/roles/configure-server/files/backend
+        - run:
+            name: Make .env file
+            command: |
+              cd backend
+              echo "ENVIRONMENT=production" > env
+              echo "NODE_ENV=production" >> env
+              echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> env
+              echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> env
+              echo "TYPEORM_HOST=$TYPEORM_HOST" >> env
+              echo "TYPEORM_PORT=$TYPEORM_PORT" >> env
+              echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> env
+              echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> env
+              echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> env
+
+        - run:
+            name: Install dependencies
+            command: |
+              # Your code here
+               exit 1
+
+              pip install awscli && apk add --update ansible 
+              cp -rv backend/*  .circleci/ansible/roles/configure-server/files/backend
+        - run: ls .circleci/ansible/roles/configure-server/files/backend
+        - run: apk update && apk add --upgrade rsync openssh
+
+        - run:
+            name: Configure server
             # Your code here
-             exit 1
-            
-            pip install awscli && apk add --update ansible 
-            cp -rv backend/*  .circleci/ansible/roles/configure-server/files/backend
-      - run: ls .circleci/ansible/roles/configure-server/files/backend
-      - run: apk update && apk add --upgrade rsync openssh     
-        
-        
-        
-            
-      - run:
-          name: Configure server
-            # Your code here
-          command: | 
-           #   exit 1
-           
-            ansible-playbook -i inventory .circleci/ansible/configure_backend.yml
-          environment:
-            ANSIBLE_HOST_KEY_CHECKING: False
-      - destroy_environment:
-              workflow_id: ${CIRCLE_WORKFLOW_ID}
+            command: |
+              #   exit 1
 
+               ansible-playbook -i inventory .circleci/ansible/configure_backend.yml
+            environment:
+              ANSIBLE_HOST_KEY_CHECKING: False
+        - destroy_environment:
+            workflow_id: ${CIRCLE_WORKFLOW_ID}
 
-# Here's where you will add some code to rollback on failure
+  # Here's where you will add some code to rollback on failure
 
   run-migrations:
     docker:
